---
- name: Check if scala is already installed
  stat: path=/opt/sbt
  register: sbt_installed


- name: Download sbt 0.13.9
  get_url: url=https://dl.bintray.com/sbt/native-packages/sbt/0.13.9/sbt-0.13.9.tgz
  args:
    dest: /tmp
  when: sbt_installed.stat.exists == False

- name: unarchive scala
  unarchive: src=/tmp/sbt-0.13.9.tgz dest=/opt copy=no
  when: sbt_installed.stat.exists == False
