---
- include: epel.yml

- name: Get Dependencies For ZeroMQ 2.1.11
  yum: name={{item}}
  with_items:
    - uuid-devel
    - pkgconfig
    - libtool
    - gcc-c++
    - libuuid-devel
- name: Check if  zeromq is already installed
  stat: path=/usr/local/lib/libzmq.so
  register: zeromq_installed


- name: Download ZeroMQ Code
  get_url: url="http://download.zeromq.org/zeromq-2.1.11.tar.gz"
  args:
    dest: /tmp/
    sha256sum: 57fa9205bda2813c6f7645d1d6016838d27bac833c1edebaecc7f3626144711a
  when: zeromq_installed.rc == 1

- name: Explode ZeroMQ Code
  unarchive: src="/tmp/zeromq-2.1.11.tar.gz" dest=/tmp/ copy=no
  when: zeromq_installed.stat.exists == False

- name: Install ZeroMQ
  script: files/install_zeromq.sh
  when: zeromq_installed.stat.exists == False
